name: Workflow
on:
  push:
    branches:
      - main

jobs:

  # BUILD 
BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalacion de Dependencias (si no está instalada)
        run: npm install

      - name: Compila y empaqueta
        run: |
          npm run build

      - name: Upload build output
        uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true

      - name: Validacion Existencia Proyecto Sonar Cloud
        id: validateProjectOnSonar
        run: |
          #pwd
          #ls -R
          set +e
          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=laboratorio-finalv1' -d 'project=laboratorio-finalv1' -d 'organization=devsecopsusachfm' -d 'visibility=public'
          if [ $? -ne 0 ]; then
          echo "Proyecto ya existe en Sonarcloud"
          echo "::set-output name=proyectoSiExiste::1"
          else
          echo "Proyecto laboratorio-final Creado Exitosamente en Sonar Cloud"
          
          echo "Rama main como rama por defecto"
          curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=laboratorio-finalv1'
          fi
          set -e

      - name: Ejecutar Análisis Sonar Cloud
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=matesaitban84_laboratorio-final \
            -Dsonar.organization=matesaitban8484 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.branch.name=main

      - name: Validando Resultado Sonar Cloud
        run: |
          projectKey="laboratorio-final"
          branchName="main"
          
          issueCount=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/issues/search?componentKeys=${projectKey}&branch=${branchName}&types=VULNERABILITY&severities=BLOCKER,CRITICAL,MAJOR" \
            | jq '.total')

          echo "Vulnerabilidades Críticas/Altas/Medias Encontradas: $issueCount"

#          if [ "$issueCount" -gt 0 ]; then
#            echo "Vulnerabilidades Encontradas Críticas, Altas o Medias. Detener Pipeline..."
#            exit 1
#          else
#            echo "Sin Vulnerabilidades Críticas, Altas Ni Medias. Continuar...."
#          fi

  # --------------------------------- Analisis de Composición de Software ---------------------------------
SCA:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: '${{ github.event.repository.name }}'
          path: '.'
          format: 'ALL'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@master
        with:
          name: dependecy-check-report
          path: ${{ github.workspace }}/reports

      - name: Validar resultado Dependency Check
        run: |
          report="reports/dependency-check-report.json"

          if [ ! -f "$report" ]; then
            echo "No se Encontro Reporte de Dependency Check. Fallo Análisis SCA."
            exit 1
          fi

          # Modifica los valores correctos de severidadcriticidad
          critical=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "high")] | length' "$report")
          high=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "high")] | length' "$report")
          medium=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "moderate")] | length' "$report")

          echo "Vulnerabilidades Críticas/Altas: $critical"
          echo "Vulnerabilidades Medias: $medium"

#          if [ "$critical" -gt 0 ] || [ "$high" -gt 0 ] || [ "$medium" -gt 0 ]; then
#            echo "Se encontraron vulnerabilidades Críticas, Altas o Medias en dependencias. Deteniendo el pipeline..."
#            exit 1
#          else
#            echo "No se encontraron vulnerabilidades críticas, altas ni medias. Continuando..."
#          fi
  # --------------------------------- Docker Build ---------------------------------

  DockerBuild:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true

      - name: Build Docker Image
        run: |
          docker build --tag matesaitban/laboratorio-final:latest .

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push matesaitban/laboratorio-final:latest
  # --------------------------------- Image Security ---------------------------------

  ImageSecurity:
    needs: DockerBuild
    runs-on: ubuntu-latest
    steps:

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Pull
        run: |
          docker pull matesaitban/laboratorio-final:latest

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: matesaitban/laboratorio-final:latest
          format: 'table'
         # exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM'
  # --------------------------------- DAST ---------------------------------

  DAST:
    needs: ImageSecurity
    runs-on: ubuntu-latest  # usa self-hosted si tienes problemas con localhost
    steps:

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Pull
        run: docker pull matesaitban/laboratorio-final:latest

      - name: Desplegar aplicación
        run: |
          docker run -d -p 3000:3000 --name devsecops-app matesaitban/laboratorio-final:latest
          sleep 30  # Esperar que arranque correctamente

      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000/'

      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-zap-report
          path: |
            report_json.json
            report_md.md
            report_html.html