name: Workflow

on:
  push:
    branches:
      - main

jobs:

  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalación de Dependencias
        run: npm install

      - name: Compila y empaqueta
        run: npm run build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true

      - name: Validación existencia proyecto SonarCloud
        id: validateProjectOnSonar
        run: |
          set +e
          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=laboratorio-finalv1' -d 'project=laboratorio-finalv1' -d 'organization=devsecopsusachfm' -d 'visibility=public'
          if [ $? -ne 0 ]; then
            echo "Proyecto ya existe en SonarCloud"
            echo "::set-output name=proyectoSiExiste::1"
          else
            echo "Proyecto laboratorio-final Creado Exitosamente en Sonar Cloud"
            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=laboratorio-finalv1'
          fi
          set -e

      - name: Ejecutar análisis SonarCloud
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=matesaitban84_laboratorio-final \
            -Dsonar.organization=matesaitban8484 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.branch.name=main

      - name: Validar resultado SonarCloud
        run: |
          projectKey="laboratorio-final"
          branchName="main"
          issueCount=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/issues/search?componentKeys=${projectKey}&branch=${branchName}&types=VULNERABILITY&severities=BLOCKER,CRITICAL,MAJOR" \
            | jq '.total')
          echo "Vulnerabilidades Críticas/Altas/Medias Encontradas: $issueCount"

  SCA:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: '${{ github.event.repository.name }}'
          path: '.'
          format: 'ALL'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/reports

      - name: Validar resultado Dependency Check
        run: |
          report="reports/dependency-check-report.json"
          if [ ! -f "$report" ]; then
            echo "No se encontró reporte de Dependency Check. Fallo análisis SCA."
            exit 1
          fi
          critical=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "high")] | length' "$report")
          high=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "high")] | length' "$report")
          medium=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "moderate")] | length' "$report")
          echo "Vulnerabilidades Críticas/Altas: $critical"
          echo "Vulnerabilidades Medias: $medium"

  DockerBuild:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true

      - name: Build Docker Image
        run: docker build --tag matesaitban/laboratorio-final:latest .

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push matesaitban/laboratorio-final:latest

  ImageSecurity:
    needs: DockerBuild
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Pull
        run: docker pull matesaitban/laboratorio-final:latest

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: matesaitban/laboratorio-final:latest
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'

  DAST:
    needs: ImageSecurity
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Pull
        run: docker pull matesaitban/laboratorio-final:latest

      - name: Desplegar aplicación
        run: |
          docker run -d -p 3000:3000 --name devsecops-app matesaitban/laboratorio-final:latest
          sleep 15

      - name: Ejecutar escaneo ZAP
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000/'
          cmd_options: '-J report_json.json -w report_md.md -r report_html.html'
          fail_action: false

      - name: Verificar archivos de reporte
        run: ls -lh

      - name: Subir reporte ZAP
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_json.json
            report_md.md
            report_html.html
